name: Build distribution

on: 
  release:
    types: [ published ]

jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: "Install dependencies"
      - run: pip install ".[dev]"

      # Extract Tag
      - name: Store version number
        if: ${{ github.event_name == 'release' }}
        id: version
        # GITHUB_REF looks like "refs/tags/0.3.1" - we need to extract the actual version without the v prefix
        run: echo "number=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

